# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-14 09:54
from __future__ import unicode_literals

import articles.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.upload_dir),
        ),
    ]
