# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-28 12:05
from __future__ import unicode_literals

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180924_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo_height',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='photo_width',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, height_field='photo_height', null=True, upload_to=articles.models.upload_dir, width_field='photo_width'),
        ),
    ]
