# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-28 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20180928_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo_height',
            field=models.PositiveIntegerField(blank=True, default=400),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo_width',
            field=models.PositiveIntegerField(blank=True, default=800),
        ),
    ]
