# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-28 17:04
from __future__ import unicode_literals

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20180928_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='photo_height',
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo_width',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.upload_dir),
        ),
    ]
