# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-12 00:24
from __future__ import unicode_literals

import books.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cover_picture', models.ImageField(blank=True, height_field=50, null=True, upload_to=books.models.upload_dir, width_field=30)),
                ('disabled', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.CharField(blank=True, default='500.00', max_length=100)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'book',
                'ordering': ('title',),
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contributor',
                'db_table': 'contributor',
                'verbose_name_plural': 'Contributors',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(to='books.Contributor'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('slug', 'title')]),
        ),
    ]
