# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-12 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='handle',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
