# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-12 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_contributor_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(blank=True, null=True, to='books.Contributor'),
        ),
    ]
