# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-12 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190412_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='member_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(blank=True, to='books.Contributor'),
        ),
    ]
