# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-14 15:59
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180914_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_dir),
        ),
    ]
