# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-26 18:59
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180926_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/img/icons/musicadence.jpg', upload_to=accounts.models.upload_dir),
        ),
    ]
