# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-28 11:12
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180928_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/hwz12fud7/image/upload/v1538131159/media/musicadence/musicadence.jpg', null=True, upload_to=accounts.models.upload_dir),
        ),
    ]
